/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */
export {
  EyevinnChannelEngineBridge,
  EyevinnChannelEngineBridgeConfig,
  createEyevinnChannelEngineBridgeInstance,
  removeEyevinnChannelEngineBridgeInstance,
  getEyevinnChannelEngineBridgeInstance
} from './generated/eyevinn-channel-engine-bridge';
export {
  ChannelEngine,
  ChannelEngineConfig,
  createChannelEngineInstance,
  removeChannelEngineInstance,
  getChannelEngineInstance
} from './generated/channel-engine';
export {
  Encore,
  EncoreConfig,
  createEncoreInstance,
  removeEncoreInstance,
  getEncoreInstance
} from './generated/encore';
export {
  EyevinnTestAdserver,
  EyevinnTestAdserverConfig,
  createEyevinnTestAdserverInstance,
  removeEyevinnTestAdserverInstance,
  getEyevinnTestAdserverInstance
} from './generated/eyevinn-test-adserver';
export {
  EyevinnChaosStreamProxy,
  EyevinnChaosStreamProxyConfig,
  createEyevinnChaosStreamProxyInstance,
  removeEyevinnChaosStreamProxyInstance,
  getEyevinnChaosStreamProxyInstance
} from './generated/eyevinn-chaos-stream-proxy';
export {
  EyevinnAutoSubtitles,
  EyevinnAutoSubtitlesConfig,
  createEyevinnAutoSubtitlesInstance,
  removeEyevinnAutoSubtitlesInstance,
  getEyevinnAutoSubtitlesInstance
} from './generated/eyevinn-auto-subtitles';
export {
  EyevinnLambdaStitch,
  EyevinnLambdaStitchConfig,
  createEyevinnLambdaStitchInstance,
  removeEyevinnLambdaStitchInstance,
  getEyevinnLambdaStitchInstance
} from './generated/eyevinn-lambda-stitch';
export {
  EyevinnFunctionScenes,
  EyevinnFunctionScenesConfig,
  createEyevinnFunctionScenesInstance,
  removeEyevinnFunctionScenesInstance,
  getEyevinnFunctionScenesInstance
} from './generated/eyevinn-function-scenes';
export {
  EyevinnPreviewHlsService,
  EyevinnPreviewHlsServiceConfig,
  createEyevinnPreviewHlsServiceInstance,
  removeEyevinnPreviewHlsServiceInstance,
  getEyevinnPreviewHlsServiceInstance
} from './generated/eyevinn-preview-hls-service';
export {
  EyevinnHlsMonitor,
  EyevinnHlsMonitorConfig,
  createEyevinnHlsMonitorInstance,
  removeEyevinnHlsMonitorInstance,
  getEyevinnHlsMonitorInstance
} from './generated/eyevinn-hls-monitor';
export {
  EyevinnCastReceiver,
  EyevinnCastReceiverConfig,
  createEyevinnCastReceiverInstance,
  removeEyevinnCastReceiverInstance,
  getEyevinnCastReceiverInstance
} from './generated/eyevinn-cast-receiver';
export {
  EyevinnFunctionProbe,
  EyevinnFunctionProbeConfig,
  createEyevinnFunctionProbeInstance,
  removeEyevinnFunctionProbeInstance,
  getEyevinnFunctionProbeInstance
} from './generated/eyevinn-function-probe';
export {
  EyevinnContinueWatchingApi,
  EyevinnContinueWatchingApiConfig,
  createEyevinnContinueWatchingApiInstance,
  removeEyevinnContinueWatchingApiInstance,
  getEyevinnContinueWatchingApiInstance
} from './generated/eyevinn-continue-watching-api';
export {
  FlyimgFlyimg,
  FlyimgFlyimgConfig,
  createFlyimgFlyimgInstance,
  removeFlyimgFlyimgInstance,
  getFlyimgFlyimgInstance
} from './generated/flyimg-flyimg';
export {
  RestorecommercePdfRenderingSrv,
  RestorecommercePdfRenderingSrvConfig,
  createRestorecommercePdfRenderingSrvInstance,
  removeRestorecommercePdfRenderingSrvInstance,
  getRestorecommercePdfRenderingSrvInstance
} from './generated/restorecommerce-pdf-rendering-srv';
export {
  BbcBrave,
  BbcBraveConfig,
  createBbcBraveInstance,
  removeBbcBraveInstance,
  getBbcBraveInstance
} from './generated/bbc-brave';
export {
  EyevinnFunctionTrim,
  EyevinnFunctionTrimConfig,
  createEyevinnFunctionTrimInstance,
  removeEyevinnFunctionTrimInstance,
  getEyevinnFunctionTrimInstance
} from './generated/eyevinn-function-trim';
export {
  DatarheiRestreamer,
  DatarheiRestreamerConfig,
  createDatarheiRestreamerInstance,
  removeDatarheiRestreamerInstance,
  getDatarheiRestreamerInstance
} from './generated/datarhei-restreamer';
export {
  OwncastOwncast,
  OwncastOwncastConfig,
  createOwncastOwncastInstance,
  removeOwncastOwncastInstance,
  getOwncastOwncastInstance
} from './generated/owncast-owncast';
export {
  OssrsSrs,
  OssrsSrsConfig,
  createOssrsSrsInstance,
  removeOssrsSrsInstance,
  getOssrsSrsInstance
} from './generated/ossrs-srs';
export {
  GwuhaolinLivego,
  GwuhaolinLivegoConfig,
  createGwuhaolinLivegoInstance,
  removeGwuhaolinLivegoInstance,
  getGwuhaolinLivegoInstance
} from './generated/gwuhaolin-livego';
export {
  EyevinnIntercomManager,
  EyevinnIntercomManagerConfig,
  createEyevinnIntercomManagerInstance,
  removeEyevinnIntercomManagerInstance,
  getEyevinnIntercomManagerInstance
} from './generated/eyevinn-intercom-manager';
export {
  ValkeyIoValkey,
  ValkeyIoValkeyConfig,
  createValkeyIoValkeyInstance,
  removeValkeyIoValkeyInstance,
  getValkeyIoValkeyInstance
} from './generated/valkey-io-valkey';
export {
  EyevinnSrtWhep,
  EyevinnSrtWhepConfig,
  createEyevinnSrtWhepInstance,
  removeEyevinnSrtWhepInstance,
  getEyevinnSrtWhepInstance
} from './generated/eyevinn-srt-whep';
export {
  DashIndustryForumLivesim2,
  DashIndustryForumLivesim2Config,
  createDashIndustryForumLivesim2Instance,
  removeDashIndustryForumLivesim2Instance,
  getDashIndustryForumLivesim2Instance
} from './generated/dash-industry-forum-livesim2';
export {
  UsefathomFathom,
  UsefathomFathomConfig,
  createUsefathomFathomInstance,
  removeUsefathomFathomInstance,
  getUsefathomFathomInstance
} from './generated/usefathom-fathom';
export {
  EyevinnEncoreCallbackListener,
  EyevinnEncoreCallbackListenerConfig,
  createEyevinnEncoreCallbackListenerInstance,
  removeEyevinnEncoreCallbackListenerInstance,
  getEyevinnEncoreCallbackListenerInstance
} from './generated/eyevinn-encore-callback-listener';
export {
  EyevinnEncorePackager,
  EyevinnEncorePackagerConfig,
  createEyevinnEncorePackagerInstance,
  removeEyevinnEncorePackagerInstance,
  getEyevinnEncorePackagerInstance
} from './generated/eyevinn-encore-packager';
export {
  SmrchyRestRsmq,
  SmrchyRestRsmqConfig,
  createSmrchyRestRsmqInstance,
  removeSmrchyRestRsmqInstance,
  getSmrchyRestRsmqInstance
} from './generated/smrchy-rest-rsmq';
export {
  MinioMinio,
  MinioMinioConfig,
  createMinioMinioInstance,
  removeMinioMinioInstance,
  getMinioMinioInstance
} from './generated/minio-minio';
export {
  PoundifdefSmoothmq,
  PoundifdefSmoothmqConfig,
  createPoundifdefSmoothmqInstance,
  removePoundifdefSmoothmqInstance,
  getPoundifdefSmoothmqInstance
} from './generated/poundifdef-smoothmq';
export {
  EyevinnEncoreTransfer,
  EyevinnEncoreTransferConfig,
  createEyevinnEncoreTransferInstance,
  removeEyevinnEncoreTransferInstance,
  getEyevinnEncoreTransferInstance
} from './generated/eyevinn-encore-transfer';
export {
  EyevinnLiveEncoding,
  EyevinnLiveEncodingConfig,
  createEyevinnLiveEncodingInstance,
  removeEyevinnLiveEncodingInstance,
  getEyevinnLiveEncodingInstance
} from './generated/eyevinn-live-encoding';
export {
  BwallbergKingsAndPigsTs,
  BwallbergKingsAndPigsTsConfig,
  createBwallbergKingsAndPigsTsInstance,
  removeBwallbergKingsAndPigsTsInstance,
  getBwallbergKingsAndPigsTsInstance
} from './generated/bwallberg-kings-and-pigs-ts';
export {
  EyevinnSmbWhipBridge,
  EyevinnSmbWhipBridgeConfig,
  createEyevinnSmbWhipBridgeInstance,
  removeEyevinnSmbWhipBridgeInstance,
  getEyevinnSmbWhipBridgeInstance
} from './generated/eyevinn-smb-whip-bridge';
export {
  EyevinnWrtcEgress,
  EyevinnWrtcEgressConfig,
  createEyevinnWrtcEgressInstance,
  removeEyevinnWrtcEgressInstance,
  getEyevinnWrtcEgressInstance
} from './generated/eyevinn-wrtc-egress';
export {
  SwaggerApiSwaggerEditor,
  SwaggerApiSwaggerEditorConfig,
  createSwaggerApiSwaggerEditorInstance,
  removeSwaggerApiSwaggerEditorInstance,
  getSwaggerApiSwaggerEditorInstance
} from './generated/swagger-api-swagger-editor';
export {
  RealeyesMediaMoeReplay,
  RealeyesMediaMoeReplayConfig,
  createRealeyesMediaMoeReplayInstance,
  removeRealeyesMediaMoeReplayInstance,
  getRealeyesMediaMoeReplayInstance
} from './generated/realeyes-media-moe-replay';
export {
  ItzgDockerMinecraftServer,
  ItzgDockerMinecraftServerConfig,
  createItzgDockerMinecraftServerInstance,
  removeItzgDockerMinecraftServerInstance,
  getItzgDockerMinecraftServerInstance
} from './generated/itzg-docker-minecraft-server';
export {
  BirmeLambda,
  BirmeLambdaConfig,
  createBirmeLambdaInstance,
  removeBirmeLambdaInstance,
  getBirmeLambdaInstance
} from './generated/birme-lambda';
export {
  LinuxserverDockerMariadb,
  LinuxserverDockerMariadbConfig,
  createLinuxserverDockerMariadbInstance,
  removeLinuxserverDockerMariadbInstance,
  getLinuxserverDockerMariadbInstance
} from './generated/linuxserver-docker-mariadb';
export {
  Alexbj75Movierecommendator,
  Alexbj75MovierecommendatorConfig,
  createAlexbj75MovierecommendatorInstance,
  removeAlexbj75MovierecommendatorInstance,
  getAlexbj75MovierecommendatorInstance
} from './generated/alexbj75-movierecommendator';
export {
  BirmeContactFormSvc,
  BirmeContactFormSvcConfig,
  createBirmeContactFormSvcInstance,
  removeBirmeContactFormSvcInstance,
  getBirmeContactFormSvcInstance
} from './generated/birme-contact-form-svc';
export {
  BirmeCaptchaSvc,
  BirmeCaptchaSvcConfig,
  createBirmeCaptchaSvcInstance,
  removeBirmeCaptchaSvcInstance,
  getBirmeCaptchaSvcInstance
} from './generated/birme-captcha-svc';
export {
  Alexbj7590stv,
  Alexbj7590stvConfig,
  createAlexbj7590stvInstance,
  removeAlexbj7590stvInstance,
  getAlexbj7590stvInstance
} from './generated/alexbj75-90stv';
export {
  AnderswassenChaosproxyConfig,
  AnderswassenChaosproxyConfigConfig,
  createAnderswassenChaosproxyConfigInstance,
  removeAnderswassenChaosproxyConfigInstance,
  getAnderswassenChaosproxyConfigInstance
} from './generated/anderswassen-chaosproxy-config';
export {
  WordpressWordpress,
  WordpressWordpressConfig,
  createWordpressWordpressInstance,
  removeWordpressWordpressInstance,
  getWordpressWordpressInstance
} from './generated/wordpress-wordpress';
export {
  OlawalejuwonmAnomalydetector,
  OlawalejuwonmAnomalydetectorConfig,
  createOlawalejuwonmAnomalydetectorInstance,
  removeOlawalejuwonmAnomalydetectorInstance,
  getOlawalejuwonmAnomalydetectorInstance
} from './generated/olawalejuwonm-anomalydetector';
export {
  AtmozSftp,
  AtmozSftpConfig,
  createAtmozSftpInstance,
  removeAtmozSftpInstance,
  getAtmozSftpInstance
} from './generated/atmoz-sftp';
export {
  JoeldelpilarTicTacVue,
  JoeldelpilarTicTacVueConfig,
  createJoeldelpilarTicTacVueInstance,
  removeJoeldelpilarTicTacVueInstance,
  getJoeldelpilarTicTacVueInstance
} from './generated/joeldelpilar-tic-tac-vue';
export {
  EyevinnQrGenerator,
  EyevinnQrGeneratorConfig,
  createEyevinnQrGeneratorInstance,
  removeEyevinnQrGeneratorInstance,
  getEyevinnQrGeneratorInstance
} from './generated/eyevinn-qr-generator';
export {
  EyevinnAppConfigSvc,
  EyevinnAppConfigSvcConfig,
  createEyevinnAppConfigSvcInstance,
  removeEyevinnAppConfigSvcInstance,
  getEyevinnAppConfigSvcInstance
} from './generated/eyevinn-app-config-svc';
export {
  ErnestocaroccaHelloWorld,
  ErnestocaroccaHelloWorldConfig,
  createErnestocaroccaHelloWorldInstance,
  removeErnestocaroccaHelloWorldInstance,
  getErnestocaroccaHelloWorldInstance
} from './generated/ernestocarocca-hello-world';
export {
  ChambanaNetDockerPodcastgen,
  ChambanaNetDockerPodcastgenConfig,
  createChambanaNetDockerPodcastgenInstance,
  removeChambanaNetDockerPodcastgenInstance,
  getChambanaNetDockerPodcastgenInstance
} from './generated/chambana-net-docker-podcastgen';
export {
  AndersnasNodecat,
  AndersnasNodecatConfig,
  createAndersnasNodecatInstance,
  removeAndersnasNodecatInstance,
  getAndersnasNodecatInstance
} from './generated/andersnas-nodecat';
export {
  BirmeOscPostgresql,
  BirmeOscPostgresqlConfig,
  createBirmeOscPostgresqlInstance,
  removeBirmeOscPostgresqlInstance,
  getBirmeOscPostgresqlInstance
} from './generated/birme-osc-postgresql';
export {
  SalesagilitySuitecrm,
  SalesagilitySuitecrmConfig,
  createSalesagilitySuitecrmInstance,
  removeSalesagilitySuitecrmInstance,
  getSalesagilitySuitecrmInstance
} from './generated/salesagility-suitecrm';
export {
  EyevinnDockerTestsrcHlsLive,
  EyevinnDockerTestsrcHlsLiveConfig,
  createEyevinnDockerTestsrcHlsLiveInstance,
  removeEyevinnDockerTestsrcHlsLiveInstance,
  getEyevinnDockerTestsrcHlsLiveInstance
} from './generated/eyevinn-docker-testsrc-hls-live';
export {
  ApacheCouchdb,
  ApacheCouchdbConfig,
  createApacheCouchdbInstance,
  removeApacheCouchdbInstance,
  getApacheCouchdbInstance
} from './generated/apache-couchdb';
export {
  EyevinnSgaiAdProxy,
  EyevinnSgaiAdProxyConfig,
  createEyevinnSgaiAdProxyInstance,
  removeEyevinnSgaiAdProxyInstance,
  getEyevinnSgaiAdProxyInstance
} from './generated/eyevinn-sgai-ad-proxy';
export {
  MickaelKerjeanFilestash,
  MickaelKerjeanFilestashConfig,
  createMickaelKerjeanFilestashInstance,
  removeMickaelKerjeanFilestashInstance,
  getMickaelKerjeanFilestashInstance
} from './generated/mickael-kerjean-filestash';
export {
  PlausibleAnalytics,
  PlausibleAnalyticsConfig,
  createPlausibleAnalyticsInstance,
  removePlausibleAnalyticsInstance,
  getPlausibleAnalyticsInstance
} from './generated/plausible-analytics';
export {
  BlueskySocialPds,
  BlueskySocialPdsConfig,
  createBlueskySocialPdsInstance,
  removeBlueskySocialPdsInstance,
  getBlueskySocialPdsInstance
} from './generated/bluesky-social-pds';
export {
  DocusealcoDocuseal,
  DocusealcoDocusealConfig,
  createDocusealcoDocusealInstance,
  removeDocusealcoDocusealInstance,
  getDocusealcoDocusealInstance
} from './generated/docusealco-docuseal';
export {
  EyevinnPdsAdmin,
  EyevinnPdsAdminConfig,
  createEyevinnPdsAdminInstance,
  removeEyevinnPdsAdminInstance,
  getEyevinnPdsAdminInstance
} from './generated/eyevinn-pds-admin';
export {
  DrawdbIoDrawdb,
  DrawdbIoDrawdbConfig,
  createDrawdbIoDrawdbInstance,
  removeDrawdbIoDrawdbInstance,
  getDrawdbIoDrawdbInstance
} from './generated/drawdb-io-drawdb';
export {
  EyevinnAiCodeReviewer,
  EyevinnAiCodeReviewerConfig,
  createEyevinnAiCodeReviewerInstance,
  removeEyevinnAiCodeReviewerInstance,
  getEyevinnAiCodeReviewerInstance
} from './generated/eyevinn-ai-code-reviewer';
export {
  SearxngSearxng,
  SearxngSearxngConfig,
  createSearxngSearxngInstance,
  removeSearxngSearxngInstance,
  getSearxngSearxngInstance
} from './generated/searxng-searxng';
export {
  DicedbDice,
  DicedbDiceConfig,
  createDicedbDiceInstance,
  removeDicedbDiceInstance,
  getDicedbDiceInstance
} from './generated/dicedb-dice';
export {
  BluewaveLabsCheckmate,
  BluewaveLabsCheckmateConfig,
  createBluewaveLabsCheckmateInstance,
  removeBluewaveLabsCheckmateInstance,
  getBluewaveLabsCheckmateInstance
} from './generated/bluewave-labs-checkmate';
export {
  SupercorpAiSupergateway,
  SupercorpAiSupergatewayConfig,
  createSupercorpAiSupergatewayInstance,
  removeSupercorpAiSupergatewayInstance,
  getSupercorpAiSupergatewayInstance
} from './generated/supercorp-ai-supergateway';
export {
  EyevinnWebRunner,
  EyevinnWebRunnerConfig,
  createEyevinnWebRunnerInstance,
  removeEyevinnWebRunnerInstance,
  getEyevinnWebRunnerInstance
} from './generated/eyevinn-web-runner';
export {
  EyevinnAdNormalizer,
  EyevinnAdNormalizerConfig,
  createEyevinnAdNormalizerInstance,
  removeEyevinnAdNormalizerInstance,
  getEyevinnAdNormalizerInstance
} from './generated/eyevinn-ad-normalizer';
export {
  ExcalidrawExcalidraw,
  ExcalidrawExcalidrawConfig,
  createExcalidrawExcalidrawInstance,
  removeExcalidrawExcalidrawInstance,
  getExcalidrawExcalidrawInstance
} from './generated/excalidraw-excalidraw';
export {
  JgraphDrawio,
  JgraphDrawioConfig,
  createJgraphDrawioInstance,
  removeJgraphDrawioInstance,
  getJgraphDrawioInstance
} from './generated/jgraph-drawio';
export {
  LmsCommunitySlimserver,
  LmsCommunitySlimserverConfig,
  createLmsCommunitySlimserverInstance,
  removeLmsCommunitySlimserverInstance,
  getLmsCommunitySlimserverInstance
} from './generated/lms-community-slimserver';
export {
  ClickhouseClickhouse,
  ClickhouseClickhouseConfig,
  createClickhouseClickhouseInstance,
  removeClickhouseClickhouseInstance,
  getClickhouseClickhouseInstance
} from './generated/clickhouse-clickhouse';
export {
  MatomoOrgMatomo,
  MatomoOrgMatomoConfig,
  createMatomoOrgMatomoInstance,
  removeMatomoOrgMatomoInstance,
  getMatomoOrgMatomoInstance
} from './generated/matomo-org-matomo';
export {
  UmamiSoftwareUmami,
  UmamiSoftwareUmamiConfig,
  createUmamiSoftwareUmamiInstance,
  removeUmamiSoftwareUmamiInstance,
  getUmamiSoftwareUmamiInstance
} from './generated/umami-software-umami';
export {
  NfrederiksenHlsViewer,
  NfrederiksenHlsViewerConfig,
  createNfrederiksenHlsViewerInstance,
  removeNfrederiksenHlsViewerInstance,
  getNfrederiksenHlsViewerInstance
} from './generated/nfrederiksen-hls-viewer';
export {
  EyevinnOpenauthPwd,
  EyevinnOpenauthPwdConfig,
  createEyevinnOpenauthPwdInstance,
  removeEyevinnOpenauthPwdInstance,
  getEyevinnOpenauthPwdInstance
} from './generated/eyevinn-openauth-pwd';
export {
  EyevinnPlayerAnalyticsEventsink,
  EyevinnPlayerAnalyticsEventsinkConfig,
  createEyevinnPlayerAnalyticsEventsinkInstance,
  removeEyevinnPlayerAnalyticsEventsinkInstance,
  getEyevinnPlayerAnalyticsEventsinkInstance
} from './generated/eyevinn-player-analytics-eventsink';
export {
  EyevinnImgAltGen,
  EyevinnImgAltGenConfig,
  createEyevinnImgAltGenInstance,
  removeEyevinnImgAltGenInstance,
  getEyevinnImgAltGenInstance
} from './generated/eyevinn-img-alt-gen';
export {
  EmedvedevSlackinExtended,
  EmedvedevSlackinExtendedConfig,
  createEmedvedevSlackinExtendedInstance,
  removeEmedvedevSlackinExtendedInstance,
  getEmedvedevSlackinExtendedInstance
} from './generated/emedvedev-slackin-extended';
export {
  EyevinnEphtokenSvc,
  EyevinnEphtokenSvcConfig,
  createEyevinnEphtokenSvcInstance,
  removeEyevinnEphtokenSvcInstance,
  getEyevinnEphtokenSvcInstance
} from './generated/eyevinn-ephtoken-svc';
export {
  PostgrestPostgrest,
  PostgrestPostgrestConfig,
  createPostgrestPostgrestInstance,
  removePostgrestPostgrestInstance,
  getPostgrestPostgrestInstance
} from './generated/postgrest-postgrest';
export {
  LogflareLogflare,
  LogflareLogflareConfig,
  createLogflareLogflareInstance,
  removeLogflareLogflareInstance,
  getLogflareLogflareInstance
} from './generated/logflare-logflare';
export {
  EyevinnPlayerAnalyticsWorker,
  EyevinnPlayerAnalyticsWorkerConfig,
  createEyevinnPlayerAnalyticsWorkerInstance,
  removeEyevinnPlayerAnalyticsWorkerInstance,
  getEyevinnPlayerAnalyticsWorkerInstance
} from './generated/eyevinn-player-analytics-worker';
export {
  EyevinnCatValidate,
  EyevinnCatValidateConfig,
  createEyevinnCatValidateInstance,
  removeEyevinnCatValidateInstance,
  getEyevinnCatValidateInstance
} from './generated/eyevinn-cat-validate';
export {
  GrafanaGrafana,
  GrafanaGrafanaConfig,
  createGrafanaGrafanaInstance,
  removeGrafanaGrafanaInstance,
  getGrafanaGrafanaInstance
} from './generated/grafana-grafana';
export {
  OpfOpenproject,
  OpfOpenprojectConfig,
  createOpfOpenprojectInstance,
  removeOpfOpenprojectInstance,
  getOpfOpenprojectInstance
} from './generated/opf-openproject';
export {
  XwikiXwikiPlatform,
  XwikiXwikiPlatformConfig,
  createXwikiXwikiPlatformInstance,
  removeXwikiXwikiPlatformInstance,
  getXwikiXwikiPlatformInstance
} from './generated/xwiki-xwiki-platform';
export {
  BoldareOpenaiAssistant,
  BoldareOpenaiAssistantConfig,
  createBoldareOpenaiAssistantInstance,
  removeBoldareOpenaiAssistantInstance,
  getBoldareOpenaiAssistantInstance
} from './generated/boldare-openai-assistant';
export {
  SuperflytvOgrafServer,
  SuperflytvOgrafServerConfig,
  createSuperflytvOgrafServerInstance,
  removeSuperflytvOgrafServerInstance,
  getSuperflytvOgrafServerInstance
} from './generated/superflytv-ograf-server';
export {
  EyevinnTamsGateway,
  EyevinnTamsGatewayConfig,
  createEyevinnTamsGatewayInstance,
  removeEyevinnTamsGatewayInstance,
  getEyevinnTamsGatewayInstance
} from './generated/eyevinn-tams-gateway';
export {
  EyevinnWasmRunner,
  EyevinnWasmRunnerConfig,
  createEyevinnWasmRunnerInstance,
  removeEyevinnWasmRunnerInstance,
  getEyevinnWasmRunnerInstance
} from './generated/eyevinn-wasm-runner';
export {
  AutomatischAutomatisch,
  AutomatischAutomatischConfig,
  createAutomatischAutomatischInstance,
  removeAutomatischAutomatischInstance,
  getAutomatischAutomatischInstance
} from './generated/automatisch-automatisch';
export {
  PgvectorPgvector,
  PgvectorPgvectorConfig,
  createPgvectorPgvectorInstance,
  removePgvectorPgvectorInstance,
  getPgvectorPgvectorInstance
} from './generated/pgvector-pgvector';
export {
  FormbricksFormbricks,
  FormbricksFormbricksConfig,
  createFormbricksFormbricksInstance,
  removeFormbricksFormbricksInstance,
  getFormbricksFormbricksInstance
} from './generated/formbricks-formbricks';
export {
  MtlynchPicoshare,
  MtlynchPicoshareConfig,
  createMtlynchPicoshareInstance,
  removeMtlynchPicoshareInstance,
  getMtlynchPicoshareInstance
} from './generated/mtlynch-picoshare';
export {
  FreescoutHelpDeskFreescout,
  FreescoutHelpDeskFreescoutConfig,
  createFreescoutHelpDeskFreescoutInstance,
  removeFreescoutHelpDeskFreescoutInstance,
  getFreescoutHelpDeskFreescoutInstance
} from './generated/freescout-help-desk-freescout';
export {
  RoundcubeRoundcubemail,
  RoundcubeRoundcubemailConfig,
  createRoundcubeRoundcubemailInstance,
  removeRoundcubeRoundcubemailInstance,
  getRoundcubeRoundcubemailInstance
} from './generated/roundcube-roundcubemail';
export {
  EyevinnDockerWrtcSfu,
  EyevinnDockerWrtcSfuConfig,
  createEyevinnDockerWrtcSfuInstance,
  removeEyevinnDockerWrtcSfuInstance,
  getEyevinnDockerWrtcSfuInstance
} from './generated/eyevinn-docker-wrtc-sfu';
export {
  EyevinnEncoreUi,
  EyevinnEncoreUiConfig,
  createEyevinnEncoreUiInstance,
  removeEyevinnEncoreUiInstance,
  getEyevinnEncoreUiInstance
} from './generated/eyevinn-encore-ui';
export {
  BirmeVideoUploader,
  BirmeVideoUploaderConfig,
  createBirmeVideoUploaderInstance,
  removeBirmeVideoUploaderInstance,
  getBirmeVideoUploaderInstance
} from './generated/birme-video-uploader';
export {
  BirmePlayoutUi,
  BirmePlayoutUiConfig,
  createBirmePlayoutUiInstance,
  removeBirmePlayoutUiInstance,
  getBirmePlayoutUiInstance
} from './generated/birme-playout-ui';
export {
  BirmeStreamGfx,
  BirmeStreamGfxConfig,
  createBirmeStreamGfxInstance,
  removeBirmeStreamGfxInstance,
  getBirmeStreamGfxInstance
} from './generated/birme-stream-gfx';
export {
  EyevinnTeleprompter,
  EyevinnTeleprompterConfig,
  createEyevinnTeleprompterInstance,
  removeEyevinnTeleprompterInstance,
  getEyevinnTeleprompterInstance
} from './generated/eyevinn-teleprompter';
export {
  MpociotClaudeCodeSlackBot,
  MpociotClaudeCodeSlackBotConfig,
  createMpociotClaudeCodeSlackBotInstance,
  removeMpociotClaudeCodeSlackBotInstance,
  getMpociotClaudeCodeSlackBotInstance
} from './generated/mpociot-claude-code-slack-bot';
export {
  EyevinnTfDeployer,
  EyevinnTfDeployerConfig,
  createEyevinnTfDeployerInstance,
  removeEyevinnTfDeployerInstance,
  getEyevinnTfDeployerInstance
} from './generated/eyevinn-tf-deployer';
export {
  AblindbergAdserverFrontend,
  AblindbergAdserverFrontendConfig,
  createAblindbergAdserverFrontendInstance,
  removeAblindbergAdserverFrontendInstance,
  getAblindbergAdserverFrontendInstance
} from './generated/ablindberg-adserver-frontend';
export {
  EyevinnJustGoLive,
  EyevinnJustGoLiveConfig,
  createEyevinnJustGoLiveInstance,
  removeEyevinnJustGoLiveInstance,
  getEyevinnJustGoLiveInstance
} from './generated/eyevinn-just-go-live';
export {
  EyevinnJoinLive,
  EyevinnJoinLiveConfig,
  createEyevinnJoinLiveInstance,
  removeEyevinnJoinLiveInstance,
  getEyevinnJoinLiveInstance
} from './generated/eyevinn-join-live';
export {
  EyevinnOpenBuilder,
  EyevinnOpenBuilderConfig,
  createEyevinnOpenBuilderInstance,
  removeEyevinnOpenBuilderInstance,
  getEyevinnOpenBuilderInstance
} from './generated/eyevinn-open-builder';
export {
  JoeldelpilarBxfManager,
  JoeldelpilarBxfManagerConfig,
  createJoeldelpilarBxfManagerInstance,
  removeJoeldelpilarBxfManagerInstance,
  getJoeldelpilarBxfManagerInstance
} from './generated/joeldelpilar-bxf-manager';
export {
  BjowestmanSrtStreamGenerator,
  BjowestmanSrtStreamGeneratorConfig,
  createBjowestmanSrtStreamGeneratorInstance,
  removeBjowestmanSrtStreamGeneratorInstance,
  getBjowestmanSrtStreamGeneratorInstance
} from './generated/bjowestman-srt-stream-generator';
export {
  BirmeVacayPlanner,
  BirmeVacayPlannerConfig,
  createBirmeVacayPlannerInstance,
  removeBirmeVacayPlannerInstance,
  getBirmeVacayPlannerInstance
} from './generated/birme-vacay-planner';
export {
  PenpotPenpot,
  PenpotPenpotConfig,
  createPenpotPenpotInstance,
  removePenpotPenpotInstance,
  getPenpotPenpotInstance
} from './generated/penpot-penpot';
export {
  EyevinnChannelScheduler,
  EyevinnChannelSchedulerConfig,
  createEyevinnChannelSchedulerInstance,
  removeEyevinnChannelSchedulerInstance,
  getEyevinnChannelSchedulerInstance
} from './generated/eyevinn-channel-scheduler';
export {
  BirmeBucketCommander,
  BirmeBucketCommanderConfig,
  createBirmeBucketCommanderInstance,
  removeBirmeBucketCommanderInstance,
  getBirmeBucketCommanderInstance
} from './generated/birme-bucket-commander';
export {
  EyevinnWebVideoReview,
  EyevinnWebVideoReviewConfig,
  createEyevinnWebVideoReviewInstance,
  removeEyevinnWebVideoReviewInstance,
  getEyevinnWebVideoReviewInstance
} from './generated/eyevinn-web-video-review';
export {
  NextcloudServer,
  NextcloudServerConfig,
  createNextcloudServerInstance,
  removeNextcloudServerInstance,
  getNextcloudServerInstance
} from './generated/nextcloud-server';
export {
  LocustioLocust,
  LocustioLocustConfig,
  createLocustioLocustInstance,
  removeLocustioLocustInstance,
  getLocustioLocustInstance
} from './generated/locustio-locust';
export {
  NolltreLabTestPrepQuiz,
  NolltreLabTestPrepQuizConfig,
  createNolltreLabTestPrepQuizInstance,
  removeNolltreLabTestPrepQuizInstance,
  getNolltreLabTestPrepQuizInstance
} from './generated/nolltre-lab-test-prep-quiz';
export {
  AblindbergChaosmaker,
  AblindbergChaosmakerConfig,
  createAblindbergChaosmakerInstance,
  removeAblindbergChaosmakerInstance,
  getAblindbergChaosmakerInstance
} from './generated/ablindberg-chaosmaker';
export {
  GrusellEncoreProfileServer,
  GrusellEncoreProfileServerConfig,
  createGrusellEncoreProfileServerInstance,
  removeGrusellEncoreProfileServerInstance,
  getGrusellEncoreProfileServerInstance
} from './generated/grusell-encore-profile-server';
